// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6i2xby1it19-laL3UO5E_TEAqUbPFeE',
    appId: '1:574554854734:web:cf106e2efbb570d40b3a1f',
    messagingSenderId: '574554854734',
    projectId: 'locatify-41e5a',
    authDomain: 'locatify-41e5a.firebaseapp.com',
    storageBucket: 'locatify-41e5a.firebasestorage.app',
    measurementId: 'G-CHDBNR62MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDYctEzBq0yk3nfEEXH-FywC2MuxNh8U',
    appId: '1:574554854734:android:a256a4f2e7eae9320b3a1f',
    messagingSenderId: '574554854734',
    projectId: 'locatify-41e5a',
    storageBucket: 'locatify-41e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOTrUVVhWgyYw-IXThFxyMcM0mHr8FiZQ',
    appId: '1:574554854734:ios:6244e782cff07f160b3a1f',
    messagingSenderId: '574554854734',
    projectId: 'locatify-41e5a',
    storageBucket: 'locatify-41e5a.firebasestorage.app',
    iosBundleId: 'com.numan.locatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOTrUVVhWgyYw-IXThFxyMcM0mHr8FiZQ',
    appId: '1:574554854734:ios:6244e782cff07f160b3a1f',
    messagingSenderId: '574554854734',
    projectId: 'locatify-41e5a',
    storageBucket: 'locatify-41e5a.firebasestorage.app',
    iosBundleId: 'com.numan.locatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6i2xby1it19-laL3UO5E_TEAqUbPFeE',
    appId: '1:574554854734:web:83fcafd0cd417bb10b3a1f',
    messagingSenderId: '574554854734',
    projectId: 'locatify-41e5a',
    authDomain: 'locatify-41e5a.firebaseapp.com',
    storageBucket: 'locatify-41e5a.firebasestorage.app',
    measurementId: 'G-N5GFCYX0X2',
  );
}
